export interface DetectedEspBoard {
  chipModel: string | null;
  chipRevision: number | null;
  chipVariant: string | null;
  chipFamily: number | null;
  chipFamilyHex: string | null;
  macAddress: string | null;
  flashSizeBytes: number | null;
  flashSizeLabel: string | null;
  flashChipId: number | null;
  flashChipIdHex: string | null;
  flashManufacturerId: number | null;
  flashManufacturerIdHex: string | null;
  flashManufacturerName: string | null;
  flashDeviceId: number | null;
  flashDeviceIdHex: string | null;
  psramSizeBytes: number | null;
  psramDetected: boolean | null;
  crystalFrequency: string | null;
  securityFlags: number | null;
  securityFlagsHex: string | null;
  flashCryptCnt: number | null;
  flashCryptCntHex: string | null;
  securityKeyPurposes: number[] | null;
  securityChipId: number | null;
  securityApiVersion: number | null;
  secureBootEnabled: boolean | null;
  flashEncryptionEnabled: boolean | null;
  bootloaderOffset: number | null;
  bootloaderOffsetHex: string | null;
  detectedAt: string;
  logs: string[];
}
